# Class: nodejs::params
#
class nodejs::params {
  $version_nodejs                       = 'nodejs-6.9.1'
  $version_npm                          = 'npm-3.10.8'
  $version_gcc                          = 'gcc*'
  $version_make                         = 'make-3.82'
  $version_oracle_instant_client_devel  = 'oracle-instantclient12.1-devel'
  $version_oracle_instant_client_basic  = 'oracle-instantclient12.1-basic'
  $dir_mod_nodejs                       = '/node/'
  $dir_deploy_mod_nodejs                = '/node/deploys'
  $dir_deploy_test                      = '/node/deploys/node-test'
  $dir_logs_nodejs                      = '/node/logs'
  $log_test_nodejs                      = '/node/logs/node-test.log'
  $rsync_shell                          = '/usr/local/bin/rsync_shell.pl'
  $rsync_home                           = '/home/rsync'
  $rsync_ssh_dir                        = '/home/rsync/.ssh'
  $rsync_ssh_key                        = '/home/rsync/.ssh/authorized_keys'
  $dir_deploy_test_app                  = '/node/deploys/node-test/app.js'
  $bash_profile                         = '/node/.bash_profile'
  $init_test_app                        = '/etc/init.d/node-test'
  $archivo_sudoers                      = '/etc/sudoers'
  $dir_mod_npm                          = '/node/.npm-global/lib/'
  $npmrc                                = '/node/.npmrc'
  $direccion_proxy                      = 'http://IP_PROXY:PUERTO_PROXY'
  $usuario_rsync                        = 'rsync'
  $grupo_rsync                          = 'rsync'
  $usuario_nodejs                       = 'node'
  $grupo_nodejs                         = 'node'
  $contacto                             = ''
  $registro                             = 'registry = "https://registry.npmjs.org/"'
  $lista_modulos                        = ''
}
