# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
        . ~/.bashrc
fi

# User specific environment and startup programs

PATH=$PATH:$HOME/.local/bin:$HOME/bin
PATH=/apps-node/.npm-global/bin:/usr/local/bin:/usr/local/sbin:~/bin/usr/local/share/npm/bin:$PATH
export PATH
NODE_PATH=/apps-node/.npm-global/lib/node_modules:$NODE_PATH
export NODE_PATH
