#!/bin/sh

#
# chkconfig: 35 99 99
# description: Node.js /home/nodejs/sample/app.js
#

. /etc/rc.d/init.d/functions

USER="node"
APP="node-test"
DAEMON="/usr/bin/node"
ROOT_DIR="/apps-node"

SERVER="$ROOT_DIR/deploys/$APP/app.js"
LOG_FILE="$ROOT_DIR/logs/$APP.log"

LOCK_FILE="/var/lock/subsys/node-$APP"

do_start()
{
        if [ ! -f "$LOCK_FILE" ] ; then
                echo -n $"Starting $SERVER: "
                runuser -l "$USER" -c "$DAEMON $SERVER &>> $LOG_FILE &" && echo_success || echo_failure
                RETVAL=$?
                echo
                [ $RETVAL -eq 0 ] && touch $LOCK_FILE
                echo
                echo "Ultimas 30 lineas del log:"
                tail -30 $LOG_FILE
        else
                echo "$SERVER is locked."
                RETVAL=1
        fi
}
do_stop()
{
        pid=`ps -aefw | grep "$DAEMON $SERVER" | grep -v " grep " | awk '{print $2}'`
        echo -n $"Stopping $SERVER: "
        kill -9 $pid > /dev/null 2>&1 && echo_success || echo_failure
        RETVAL=$?
        echo
        proc=`ps -aefw | grep "$DAEMON $SERVER" | grep -v " grep " | awk '{print $2}' | wc -l`
        [ $proc -eq 0 ] && rm -f $LOCK_FILE
        [ $RETVAL -eq 0 ] && rm -f $LOCK_FILE
}
do_status()
{
        if [ ! -f "$LOCK_FILE" ] ; then
                echo -n $"Stopped" && echo_failure
                echo
        else
                proc=`ps -aefw | grep "$DAEMON $SERVER" | grep -v " grep " | awk '{print $2}' | wc -l`
                if [ $proc -eq 0 ] ; then
                        echo -n $"Stopped" && echo_failure
                        echo
                else
                        echo -n $"Running" && echo_success
                        echo
                fi
        fi
}
case "$1" in
        start)
                do_start
                ;;
        stop)
                do_stop
                ;;
        status)
                do_status
                ;;
        restart)
                do_stop
                do_start
                ;;
        *)
                echo "Usage: $0 {start|stop|restart}"
                RETVAL=1
esac

exit $RETVAL
